import Auth from './pages/Auth';import {useAuth} from './context/AuthContext';import {useCloudSync} from './hooks/useCloudSync';
import {useEffect,useState} from 'react';
import Navigation from './components/Navigation';import TopBar from './components/TopBar';import Modal from './components/Modal';
import Home from './pages/Home';import Play from './pages/Play';import SpeedCount from './pages/SpeedCount';import CountDrill from './pages/CountDrill';import TrueCount from './pages/TrueCount';import StrategyTrainer from './pages/StrategyTrainer';import Statistics from './pages/Statistics';import Learn from './pages/Learn';import Settings from './pages/Settings';import {useLocalStorage} from './hooks/useLocalStorage';import {useStatistics} from './hooks/useStatistics';
const defaults={decks:6,hitSoft17:false,blackjackPayout:1.5,doubleAfterSplit:true,maxSplits:3,splitAcesOneCard:true,penetration:.75,gameSpeed:'normal',sound:false,animations:true,countSystem:'hilo',difficulty:'beginner',showRunningCount:false,showTrueCount:true,showDecksRemaining:true,showCardValues:false,indexDeviations:false,trueCountRounding:'truncate'};
export default function App(){const {user,loading,configured}=useAuth();const [page,setPage]=useLocalStorage('cc_last_page','home'),[settings,setSettings]=useLocalStorage('cc_settings',defaults),[balance,setBalance]=useLocalStorage('cc_balance',10000),[tutorial,setTutorial]=useLocalStorage('cc_tutorial',false);const [focus,setFocus]=useState(false),[tutorialStep,setTutorialStep]=useState(0);const statsApi=useStatistics();const syncStatus=useCloudSync({user,settings,setSettings,stats:statsApi.stats,setStats:statsApi.setStats,balance,setBalance});
 useEffect(()=>{const today=new Date().toISOString().slice(0,10);if(!statsApi.stats.practiceDates?.includes(today)&&['play','speed','drill','true','strategy'].includes(page))statsApi.setStats(s=>({...s,practiceDates:[...(s.practiceDates||[]),today].slice(-365)}))},[page]);
 const props={settings,setSettings,balance,setBalance,statsApi,setPage};let content;if(page==='home')content=<Home setPage={setPage} stats={statsApi.stats}/>;else if(page==='play')content=<Play {...props}/>;else if(page==='speed')content=<SpeedCount statsApi={statsApi}/>;else if(page==='drill')content=<CountDrill settings={settings} statsApi={statsApi}/>;else if(page==='true')content=<TrueCount settings={settings} statsApi={statsApi}/>;else if(page==='strategy')content=<StrategyTrainer settings={settings} statsApi={statsApi}/>;else if(page==='stats')content=<Statistics stats={statsApi.stats}/>;else if(page==='learn')content=<Learn/>;else content=<Settings {...props}/>;
 const slides=[['Learn Blackjack Card Counting','Train Blackjack decisions and Hi-Lo counting together.'],['Low cards increase the count','Cards 2 through 6 are +1.'],['High cards decrease the count','10s, face cards and Aces are −1.'],['Keep the running count','Only count cards once they are visible to you.'],['Convert to true count','Divide the running count by estimated decks remaining.']];
 if(loading)return <div className="auth-loading">Loading secure session…</div>;if(!configured)return <div className="auth-loading"><div><h2>Supabase setup required</h2><p>Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to .env.local.</p></div></div>;if(!user)return <Auth/>;return <div className={`app ${focus?'focus':''}`}><Navigation page={page} setPage={setPage} focus={focus}/><main><TopBar stats={statsApi.stats} focus={focus} setFocus={setFocus} user={user} syncStatus={syncStatus}/>{content}</main><Modal open={!tutorial} title={slides[tutorialStep][0]}><div className="onboarding"><div className="onboard-symbol">{['♠','+1','−1','∑','÷'][tutorialStep]}</div><p>{slides[tutorialStep][1]}</p><div className="dots">{slides.map((_,i)=><i key={i} className={i===tutorialStep?'active':''}/>)}</div><div className="onboard-actions"><button className="secondary-btn" onClick={()=>setTutorial(true)}>Skip Tutorial</button><button className="gold-btn" onClick={()=>tutorialStep<4?setTutorialStep(x=>x+1):setTutorial(true)}>{tutorialStep<4?'Next':'Start Training'}</button></div></div></Modal></div>}
